### ISSUE TITLE
Hint card

### ISSUE THREAD

**Issue by s-wu** [stevenhao/set#43]
Have an option to get a hint (e.g. Shift+H). Highlights a single card of a valid set.

**Comment by stevenhao** [comment]
+1. Should card be randomly chosen from a randomly chosen set, or randomly chosen from union of all sets?

**Comment by s-wu** [comment]
Don't have a strong preference. I think even the first card of the first set is passable

**Comment by stevenhao** [comment]
closed by https://github.com/stevenhao/set/commit/aa466c4a5e55d465e36c58e9a4c371ea6b0e325c
